-- ============================================================
--  BizInsight — Database Setup SQL
--  Run this file in phpMyAdmin or MySQL CLI ONCE to set up
--  the database, tables, and demo data.
--
--  Steps:
--  1. Open phpMyAdmin → SQL tab
--  2. Paste this entire file and click Go
--  OR via terminal:  mysql -u root -p < database/setup.sql
-- ============================================================

-- Create & select database
CREATE DATABASE IF NOT EXISTS bizinsight_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE bizinsight_db;

-- ============================================================
--  TABLE: users
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  name          VARCHAR(100)  NOT NULL,
  email         VARCHAR(150)  NOT NULL UNIQUE,
  password      VARCHAR(255)  NOT NULL,
  business_name VARCHAR(150)  DEFAULT '',
  business_type VARCHAR(80)   DEFAULT '',
  phone         VARCHAR(30)   DEFAULT '',
  city          VARCHAR(80)   DEFAULT '',
  gst           VARCHAR(30)   DEFAULT '',
  currency      VARCHAR(10)   DEFAULT 'INR',
  created_at    DATETIME      DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
--  TABLE: sales
-- ============================================================
CREATE TABLE IF NOT EXISTS sales (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  user_id       INT           NOT NULL,
  product_name  VARCHAR(150)  NOT NULL,
  category      VARCHAR(80)   DEFAULT 'Other',
  sales_amount  DECIMAL(12,2) NOT NULL DEFAULT 0,
  profit        DECIMAL(12,2) DEFAULT 0,
  quantity      INT           DEFAULT 0,
  month_name    VARCHAR(20)   NOT NULL,
  created_at    DATETIME      DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_user_id   (user_id),
  INDEX idx_month     (month_name),
  INDEX idx_category  (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
--  TABLE: uploads  (tracks CSV import history)
-- ============================================================
CREATE TABLE IF NOT EXISTS uploads (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  user_id          INT         NOT NULL,
  file_name        VARCHAR(255) NOT NULL,
  records_imported INT         DEFAULT 0,
  uploaded_at      DATETIME    DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
--  DEMO USER  (password = Demo@1234)
--  IMPORTANT: Do NOT insert the password hash directly here.
--  Instead, run the PHP setup script after this SQL:
--    http://localhost/bizinsight/setup_demo.php
--  That script inserts the demo user with a correct bcrypt hash.
--  OR: use the INSERT below which uses a known-good bcrypt hash
--  for the password "Demo@1234" generated by PHP password_hash().
-- ============================================================
INSERT IGNORE INTO users
  (name, email, password, business_name, business_type, phone, city, currency)
VALUES (
  'Demo User',
  'demo@bizinsight.com',
  '$2y$10$egBS5qrFD8IB/8tz.WYuJ.KahEGzrEcWvWNmdsAPuv8..e6QxiLpW',
  'Demo Business Co.',
  'Retail Store',
  '+91 98765 43210',
  'Mumbai, India',
  'INR'
);
-- Note: If the above hash does not work, visit http://localhost/bizinsight/setup_demo.php
-- to auto-insert the demo user with a freshly generated hash.

-- ============================================================
--  DEMO SALES DATA  (linked to demo user id=1)
--  INSERT IGNORE prevents duplicate errors on re-run
-- ============================================================
INSERT IGNORE INTO sales (user_id, product_name, category, sales_amount, profit, quantity, month_name) VALUES
(1, 'Laptop Pro X1',          'Electronics',  50000,  8000,  5,  'January'),
(1, 'Mobile Galaxy S23',      'Phones',        30000,  5000,  8,  'January'),
(1, 'Smart TV 55" UHD',       'Electronics',  45000,  7200,  3,  'February'),
(1, 'Wireless Headphones Pro','Audio',         12000,  3500, 12,  'February'),
(1, 'Tablet Pro Z Ultra',     'Tablets',       25000,  4100,  4,  'February'),
(1, 'Gaming Mouse Elite',     'Accessories',   18000,  5400, 20,  'March'),
(1, 'Laptop Pro X1',          'Electronics',  55000,  9000,  5,  'March'),
(1, 'Bluetooth Speaker Mini', 'Audio',          8000,  2400, 10,  'March'),
(1, 'Mobile Galaxy S23',      'Phones',        36000,  6000,  9,  'April'),
(1, 'Smart TV 65" 4K',        'Electronics',  75000, 12000,  3,  'April'),
(1, 'Wireless Keyboard',      'Accessories',    6500,  1950,  8,  'April'),
(1, 'Tablet Pro Z Ultra',     'Tablets',       30000,  5000,  5,  'May'),
(1, 'Laptop Pro X2',          'Electronics',  65000, 10500,  6,  'May'),
(1, 'Mobile iPhone 15',       'Phones',        80000, 12000,  8,  'May'),
(1, 'Noise Cancelling ANC',   'Audio',         22000,  6600, 11,  'May'),
(1, 'Laptop Pro X2',          'Electronics',  70000, 11500,  7,  'June'),
(1, 'Smart TV 55" UHD',       'Electronics',  45000,  7200,  3,  'June'),
(1, 'Mobile Galaxy S24',      'Phones',        40000,  7000,  8,  'June'),
(1, 'Gaming Headset Pro',     'Audio',         15000,  4500,  9,  'June'),
(1, 'USB-C Hub Premium',      'Accessories',    4500,  1350, 18,  'June');

-- ============================================================
--  Confirm setup
-- ============================================================
SELECT 'BizInsight database setup complete!' AS Status;
SELECT CONCAT('Demo login → Email: demo@bizinsight.com | Password: Demo@1234') AS DemoCredentials;
